const EVENTS = {
    START_RECORDING: 'START_RECORDING',
    STOP_RECORDING: 'STOP_RECORDING',
    PAUSE_RECORDING: 'PAUSE_RECORDING',
    RESUME_RECORDING: 'RESUME_RECORDING',
    EXTENSION_CONNECTED: 'EXTENSION_CONNECTED',
    EXTENSION_DISCONNECTED: 'EXTENSION_DISCONNECTED',
    RECORDER_DATA:'RECORDER_DATA'
}
module.exports = EVENTS